from networkx import Graph
from engine import Scheme, SwitchManager, Pin, COLOR

from elements.generic_car_elements import Akb, Light, Relay, Starter, SimpleSwitch, Consumer

'''
graph = Graph()
sm = SwitchManager()
uaz = Scheme(graph, sm)

ground = Pin(uaz, "Масса (кузов)")
akb = Akb(uaz, "Аккумулятор", 12.0)

ground_switch = SimpleSwitch("Размыкатель массы")

starter = Starter(uaz, "Стартер", 300, 20)

generator = Generator(uaz, "Генератор")

ignition_input_pin = Pin(uaz, "Разветвитель для питания катушек зажигания")
ignition_coil_1 = Consumer(uaz, "Катушка 1", 8)
ignition_coil_2 = Consumer(uaz, "Катушка 2", 8)

winch = Consumer(uaz, "Лебедка", 300)

coolant_fan_1 = Consumer(uaz, "Э-вент охл ДВС 1", 8)
coolant_fan_2 = Consumer(uaz, "Э-вент охл ДВС 2", 8)


coolant_sensor = Sensor(uaz, "Датчик вкл э-вент охл ДВС")
engine_overheat_sensor = Sensor(uaz, "Датчик перегрева охлаждающей жидкости")
engine_temp_sensor = Sensor("Датчик температуры охлаждающей жидкости")
'''



m = Ground(uaz, "Кузов")
ground_switch = SimpleSwitch(uaz, "Размыкатель массы")
akb = Akb(uaz, "Аккумулятор", 12.0)
starter = Starter(uaz, "Стартер", 300, 20)
generator = Generator(uaz, "Генератор")
ignition = Pin(uaz, "Система зажигания")
winch = Winch(uaz, "Лебедка", 300)
winch_relay = Relay(uaz, "winch_relay")
winch_fuse = Fuse(uaz, "winch_fuse")
winch_switch = SimpleSwitch(uaz, "winch_switch")
coolant_fan_1 = Fan(uaz, "Э-вент охл ДВС 1", 8)
coolant_fan_2 = Fan(uaz, "Э-вент охл ДВС 2", 8)
coolant_sensor = Sensor(uaz, "Датчик вкл э-вент охл ДВС")
engine_overheat_sensor = Sensor(uaz, "Датчик перегрева охлаждающей жидкости")
engine_temp_sensor = Sensor(uaz, "Датчик температуры охлаждающей жидкости")
low_oil_pressure_sensor = Sensor(uaz, "Датчик низкого давления масла")
oil_pressure_sensor = Sensor(uaz, "Датчик давления масла")
car_horn = CarHorn(uaz, "Гудок", 15)
left_low_beam = Light(uaz, "Левый ближний свет", 15)
left_high_beam = Light(uaz, "Левый дальний свет", 15)
front_left_side_light = Light(uaz, "Передний левый габарит", 15)
left_front_turn_signal = Light(uaz, "Левый передний поворотник", 15)
left_turn_signal_repeater = Light(uaz, "Левый повторитель поворотника", 15)
right_low_beam = Light(uaz, "Правый ближний свет", 15)
right_high_beam = Light(uaz, "Правый дальний свет", 15)
front_right_side_light = Light(uaz, "Передний правый габарит", 15)
right_front_turn_signal = Light(uaz, "Правый передний поворотник", 15)
right_turn_signal_repeater = Light(uaz, "Правый повторитель поворотника", 15)
electric_pump = ElectricPump(uaz, "Электрическая помпа", 15)
front_head_light = Light(uaz, "Передняя люстра", 15)
rear_head_light = Light(uaz, "Задняя люстра", 15)
left_head_light = Light(uaz, "Левая боковая люстра", 15)
right_head_light = Light(uaz, "Правая боковая люстра", 15)
power_fuse = Fuse(uaz, "Силовой предохранитель")
heater = Heater(uaz, "Отопитель салона", 15)
heater_resistor = Resistor(uaz, "Резистор печки салона", 15)
interior_fan = Fan(uaz, "Вентилятор салона", 8)
wipers = Wipers(uaz, "Дворники", 15)
windshield_washer = WinshieldWasher(uaz, "Омыватель лобового стекла", 15)
brake_pressure_sensor = Sensor(uaz, "Датчик нажатия педали тормоза")
reverse_lamp_sensor = Sensor(uaz, "Датчик движения заднего хода")
low_brake_fluid_sensor = Sensor(uaz, "Датчик недостаточного уровня тормозной жидкости")
fuel_level_sensor = Sensor(uaz, "Датчик уровня топлива")
lower_ground_splitter = Pin(uaz, "Нижний разветвитель массы")
power_splitter = Pin(uaz, "Силовой разветвитель")
upper_ground_splitter = Pin(uaz, "Верхний разветвитель массы")
direct_consumer_fuse_splitter = Pin(uaz, "Разветвитель для предохранителей прямых потребителей")
coolant_fan_1_fuse = Fuse(uaz, "Прд э-вент охл ДВС 1.")
coolant_fan_2_fuse = Fuse(uaz, "Прд э-вент охл ДВС 2.")
low_beam_relay_fuse = Fuse(uaz, "Прд. реле ближн света")
high_beam_relay_fuse = Fuse(uaz, "Прд. реле дальн света")
side_light_relay_fuse = Fuse(uaz, "Прд. реле габаритов")
turn_signal_fuse = Fuse(uaz, "Прд. поворотников")
wipers_fuse = Fuse(uaz, "Прд. дворников")
windshield_washer_fuse = Fuse(uaz, "Прд. моторчика омывайки")
heater_fuse = Fuse(uaz, "Прд. отопителя")
interior_fan_fuse = Fuse(uaz, "Прд. вентилятора салона")
car_horn_fuse = Fuse(uaz, "Прд. гудка")
electric_pump_fuse = Fuse(uaz, "Прд. электрической помпы")
starter_relay = Relay5(uaz, "Реле стартера")
ignition_relay = Relay(uaz, "Реле зажигания")
coolant_fan_1_relay = Relay(uaz, "Реле э-вент охл ДВС 1")
coolant_fan_2_relay = Relay(uaz, "Реле э-вент охл ДВС 2")
low_beam_relay = Relay(uaz, "Реле ближнего света")
high_beam_relay = Relay(uaz, "Реле дальнего света")
side_light_relay = Relay(uaz, "Реле габаритов")
windshield_washer_relay = Relay(uaz, "Реле моторчика омывайки")
turn_signal_relay = Relay(uaz, "Реле поворотников")
wipers_relay = Relay(uaz, "Реле дворников")
front_head_light_relay = Relay(uaz, "Реле передней люстры")
rear_head_light_relay = Relay(uaz, "Реле задней люстры")
left_head_light_relay = Relay(uaz, "Реле левой боковой люстры")
right_head_light_relay = Relay(uaz, "Реле правой боковой люстры")
heater_relay_1 = Relay(uaz, "Реле отопителя (1-я скорость)")
heater_relay_2 = Relay(uaz, "Реле отопителя (2-я скорость)")
interior_fan_relay = Relay(uaz, "Реле вентилятора салона")
car_horn_relay = Relay(uaz, "Реле гудка")
electric_pump_relay = Relay(uaz, "Реле электрической помпы")
starter_relay_fuse = Fuse(uaz, "Прд реле стартера.")
extra_stuff_fuse_splitter = Pin(uaz, "Разветвитель для предохранителей доп оборудования")
front_head_light_fuse = Fuse(uaz, "Прд. передней люстры")
rear_head_light_fuse = Fuse(uaz, "Прд. задней люстры")
left_head_light_fuse = Fuse(uaz, "Прд. левой боковой люстры")
right_head_light_fuse = Fuse(uaz, "Прд. правой боковой люстры")
control_line_from_ignition_1 = Pin(uaz, "Потребители управляющей линии от зажигания (свет)")
control_line_from_ignition_2 = Pin(uaz, "Потребители управляющей линии от зажигания (прочее)")
control_line_from_ignition_fuse = Fuse(uaz, "Предохранитель потребителей управляющей линии от зажигания")
side_light_splitter = Pin(uaz, "разветвитель габаритов")
turn_signal_control_light = Light(uaz, "Контрольная лампа поворотников", 15)
low_brake_fluid_warning_light = Light(uaz, "Контрольная лампа недостаточного уровня тормозной жидкости", 15)
high_beam_control_light = Light(uaz, "Контрольная лампа дальнего света", 15)
speedometer_backlight = Light(uaz, "Подсветка спидометра", 15)
fuel_level_backlight = Light(uaz, "Подсветка датчика уровня топлива", 15)
fuel_level_gauge = Gauge(uaz, "Указатель уровня топлива", 15)
engine_temp_backlight = Light(uaz, "Подсветка датчика температуры двигателя", 15)
engine_temp_gauge = Gauge(uaz, "Указатель температуры двигателя", 15)
engine_overheat_control_light = Light(uaz, "Лампа перегрева двигателя", 15)
oil_pressure_backlight = Light(uaz, "Подсветка датчика давления масла в двигателе", 15)
oil_pressure_gauge = Gauge(uaz, "Указатель давления масла в двигателе", 15)
low_oil_pressure_control_light = Light(uaz, "Лампа низкого давления масла в двигателе", 15)
voltmeter_backlight = Light(uaz, "Подсветка вольтметра", 15)
voltmeter_gauge = Gauge(uaz, "Указатель вольтметра", 15)
ignition_switch = SimpleSwitch(uaz, "Выключатель зажигания")
start_button = SimpleSwitch(uaz, "Кнопка Старт")
coolant_control_switch = Switch3States6Pins(uaz, "Переключатель упр э-вент охл ДВС")
light_switch = SimpleSwitch(uaz, "Выключатель габаритов и ближнего света")
emergency_light_button = SimpleSwitch(uaz, "Кнопка аварийной сигнализации")
front_head_light_switch = SimpleSwitch(uaz, "Выключатель передней люстры")
rear_head_light_switch = SimpleSwitch(uaz, "Выключатель задней люстры")
left_head_light_switch = SimpleSwitch(uaz, "Выключатель левой боковой люстры")
right_head_light_switch = SimpleSwitch(uaz, "Выключатель правой боковой люстры")
car_horn_switch = SimpleSwitch(uaz, "Кнопка гудка")
heater_switch = Switch3States6Pins(uaz, "Переключатель печки")
interior_fan_switch = SimpleSwitch(uaz, "Выключатель салонного вентилятора")
electric_pump_switch = SimpleSwitch(uaz, "Выключатель электрической помпы")
left_steering_column_light_switch = SimpleSwitch(uaz, "Левый подрулевой переключатель освещения")
left_steering_column_turn_signal_switch = SimpleSwitch(uaz, "левый подрулевой переключатель поворотников")
right_steering_column_switch = SimpleSwitch(uaz, "правый подрулевой переключатель")
rear_left_side_light = Light(uaz, "Задний левый габарит", 15)
left_rear_turn_signal = Light(uaz, "Левый задний поворотник", 15)
left_stop_signal = Light(uaz, "Левый стоп-сигнал", 15)
rear_right_side_light = Light(uaz, "Задний правый габарит", 15)
right_rear_turn_signal = Light(uaz, "Правый задний поворотник", 15)
right_stop_signal = Light(uaz, "Правый стоп-сигнал", 15)
number_plate_light = Light(uaz, "Подсветка номера", 15)
reverse_lamp = Light(uaz, "Лампа заднего хода", 15)
extra_stop_signal = Light(uaz, "Доп. стоп-сигнал", 15)
stop_signal_splitter = Pin(uaz, "разветвитель стоп сигналов")

ground_switch.in.addConnectionTo(m.ground, 0, 0, COLOR.Black)
generator.minus.addConnectionTo(m.ground, 0.1, 25.0, COLOR.black)
ground_switch.out.addConnectionTo(ground_switch.in, 0, 0, COLOR.Black)
akb.minus.addConnectionTo(ground_switch.out, 0.3, 50.0, COLOR.black)
akb.plus.addConnectionTo(akb.power_source, 0, 0, COLOR.Black)
starter.plus.addConnectionTo(akb.plus, 1.5, 50.0, COLOR.red)
winch.plus.addConnectionTo(akb.plus, 1.5, 50.0, COLOR.red)
power_fuse.in.addConnectionTo(akb.plus, 1.35, 25.0, COLOR.red)
akb.power_source.addConnectionTo(akb.minus, 0, 0, COLOR.Black)
starter.eng.addConnectionTo(starter.plus, 0, 0, COLOR.Black)
starter.g.addConnectionTo(starter.eng, 0, 0, COLOR.Black)
starter.st_relay.addConnectionTo(starter.st, 0, 0, COLOR.Black)
m.ground.addConnectionTo(starter.g, 0, 0, COLOR.Black)
starter.g.addConnectionTo(starter.st_relay, 0, 0, COLOR.Black)
starter.plus.addConnectionTo(generator.plus, 1.0, 50.0, COLOR.red)
generator.power_source.addConnectionTo(generator.minus, 0, 0, COLOR.Black)
generator.plus.addConnectionTo(generator.power_source, 0, 0, COLOR.Black)
m.ground.addConnectionTo(generator.g, 0, 0, COLOR.Black)
generator.g.addConnectionTo(generator.v, 0, 0, COLOR.Black)
ignition.ignition_coil_1_pin.addConnectionTo(ignition.data, 2.5, 2.5, COLOR.blue)
ignition.ignition_coil_2_pin.addConnectionTo(ignition.data, 2.5, 2.5, COLOR.blue)
ignition.ignition_coil_1.addConnectionTo(ignition.ignition_coil_1_pin, 0, 0, COLOR.Black)
ignition.ignition_coil_2.addConnectionTo(ignition.ignition_coil_2_pin, 0, 0, COLOR.Black)
ignition.g.addConnectionTo(ignition.ignition_coil_1, 0, 0, COLOR.Black)
ignition.g.addConnectionTo(ignition.ignition_coil_2, 0, 0, COLOR.Black)
m.ground.addConnectionTo(ignition.g, 0, 0, COLOR.Black)
winch_fuse.in.addConnectionTo(winch.plus, 0, 0, COLOR.Black)
m.ground.addConnectionTo(winch.minus, 1.5, 50.0, COLOR.black)
winch.minus.addConnectionTo(winch.winch, 0, 0, COLOR.Black)
winch_relay._87.addConnectionTo(winch_relay._30, 0, 0, COLOR.Black)
winch.winch.addConnectionTo(winch_relay._87, 0, 0, COLOR.Black)
winch.minus.addConnectionTo(winch_relay._86, 0, 0, COLOR.Black)
winch_relay.coil.addConnectionTo(winch_relay._85, 0, 0, COLOR.Black)
winch_relay._86.addConnectionTo(winch_relay.coil, 0, 0, COLOR.Black)
winch_fuse.out.addConnectionTo(winch_fuse.in, 0, 0, COLOR.Black)
winch_relay._30.addConnectionTo(winch_fuse.out, 0, 0, COLOR.Black)
winch_switch.in.addConnectionTo(winch_fuse.out, 0, 0, COLOR.Black)
winch_switch.out.addConnectionTo(winch_switch.in, 0, 0, COLOR.Black)
winch_relay._85.addConnectionTo(winch_switch.out, 0, 0, COLOR.Black)
coolant_fan_1.motor.addConnectionTo(coolant_fan_1.plus, 0, 0, COLOR.Black)
m.ground.addConnectionTo(coolant_fan_1.minus, 0.3, 0.5, COLOR.black)
coolant_fan_1.minus.addConnectionTo(coolant_fan_1.motor, 0, 0, COLOR.Black)
coolant_fan_2.motor.addConnectionTo(coolant_fan_2.plus, 0, 0, COLOR.Black)
m.ground.addConnectionTo(coolant_fan_2.minus, 0.3, 0.5, COLOR.black)
coolant_fan_2.minus.addConnectionTo(coolant_fan_2.motor, 0, 0, COLOR.Black)
coolant_sensor.out.addConnectionTo(coolant_sensor.in, 0, 0, COLOR.Black)
m.ground.addConnectionTo(coolant_sensor.out, 0, 0, COLOR.Black)
engine_overheat_sensor.out.addConnectionTo(engine_overheat_sensor.in, 0, 0, COLOR.Black)
m.ground.addConnectionTo(engine_overheat_sensor.out, 0, 0, COLOR.Black)
engine_temp_sensor.out.addConnectionTo(engine_temp_sensor.in, 0, 0, COLOR.Black)
m.ground.addConnectionTo(engine_temp_sensor.out, 0, 0, COLOR.Black)
low_oil_pressure_sensor.out.addConnectionTo(low_oil_pressure_sensor.in, 0, 0, COLOR.Black)
m.ground.addConnectionTo(low_oil_pressure_sensor.out, 0, 0, COLOR.Black)
oil_pressure_sensor.out.addConnectionTo(oil_pressure_sensor.in, 0, 0, COLOR.Black)
m.ground.addConnectionTo(oil_pressure_sensor.out, 0, 0, COLOR.Black)
car_horn.horn.addConnectionTo(car_horn.plus, 0, 0, COLOR.Black)
m.ground.addConnectionTo(car_horn.minus, 0.5, 2.5, COLOR.black)
car_horn.minus.addConnectionTo(car_horn.horn, 0, 0, COLOR.Black)
left_low_beam.lamp.addConnectionTo(left_low_beam.plus, 0, 0, COLOR.Black)
left_low_beam.minus.addConnectionTo(left_low_beam.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(left_low_beam.minus, 1.0, 1.5, COLOR.black)
left_high_beam.lamp.addConnectionTo(left_high_beam.plus, 0, 0, COLOR.Black)
left_high_beam.minus.addConnectionTo(left_high_beam.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(left_high_beam.minus, 0.5, 1.0, COLOR.black)
front_left_side_light.lamp.addConnectionTo(front_left_side_light.plus, 0, 0, COLOR.Black)
front_left_side_light.minus.addConnectionTo(front_left_side_light.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(front_left_side_light.minus, 1.0, 0.5, COLOR.black)
left_front_turn_signal.lamp.addConnectionTo(left_front_turn_signal.plus, 0, 0, COLOR.Black)
left_front_turn_signal.minus.addConnectionTo(left_front_turn_signal.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(left_front_turn_signal.minus, 0.5, 1.0, COLOR.black)
left_turn_signal_repeater.lamp.addConnectionTo(left_turn_signal_repeater.plus, 0, 0, COLOR.Black)
left_front_turn_signal.plus.addConnectionTo(left_turn_signal_repeater.plus, 2.0, 0.75, COLOR.violet)
left_turn_signal_repeater.minus.addConnectionTo(left_turn_signal_repeater.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(left_turn_signal_repeater.minus, 0.5, 1.0, COLOR.black)
right_low_beam.lamp.addConnectionTo(right_low_beam.plus, 0, 0, COLOR.Black)
right_low_beam.minus.addConnectionTo(right_low_beam.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(right_low_beam.minus, 1.0, 1.5, COLOR.black)
right_high_beam.lamp.addConnectionTo(right_high_beam.plus, 0, 0, COLOR.Black)
right_high_beam.minus.addConnectionTo(right_high_beam.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(right_high_beam.minus, 0.5, 1.0, COLOR.black)
front_right_side_light.lamp.addConnectionTo(front_right_side_light.plus, 0, 0, COLOR.Black)
front_right_side_light.minus.addConnectionTo(front_right_side_light.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(front_right_side_light.minus, 1.0, 0.5, COLOR.black)
right_front_turn_signal.lamp.addConnectionTo(right_front_turn_signal.plus, 0, 0, COLOR.Black)
right_front_turn_signal.minus.addConnectionTo(right_front_turn_signal.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(right_front_turn_signal.minus, 0.5, 0.5, COLOR.black)
right_turn_signal_repeater.lamp.addConnectionTo(right_turn_signal_repeater.plus, 0, 0, COLOR.Black)
right_front_turn_signal.plus.addConnectionTo(right_turn_signal_repeater.plus, 3.0, 0.75, COLOR.red)
right_turn_signal_repeater.minus.addConnectionTo(right_turn_signal_repeater.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(right_turn_signal_repeater.minus, 0.5, 0.5, COLOR.black)
electric_pump.motor.addConnectionTo(electric_pump.plus, 0, 0, COLOR.Black)
m.ground.addConnectionTo(electric_pump.minus, 0.5, 1.5, COLOR.black)
electric_pump.minus.addConnectionTo(electric_pump.motor, 0, 0, COLOR.Black)
front_head_light.lamp.addConnectionTo(front_head_light.plus, 0, 0, COLOR.Black)
front_head_light.minus.addConnectionTo(front_head_light.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(front_head_light.minus, 2.0, 6.0, COLOR.black)
rear_head_light.lamp.addConnectionTo(rear_head_light.plus, 0, 0, COLOR.Black)
rear_head_light.minus.addConnectionTo(rear_head_light.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(rear_head_light.minus, 2.5, 6.0, COLOR.black)
left_head_light.lamp.addConnectionTo(left_head_light.plus, 0, 0, COLOR.Black)
left_head_light.minus.addConnectionTo(left_head_light.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(left_head_light.minus, 3.0, 6.0, COLOR.black)
right_head_light.lamp.addConnectionTo(right_head_light.plus, 0, 0, COLOR.Black)
right_head_light.minus.addConnectionTo(right_head_light.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(right_head_light.minus, 2.0, 6.0, COLOR.black)
power_fuse.out.addConnectionTo(power_fuse.in, 0, 0, COLOR.Black)
power_splitter.pin.addConnectionTo(power_fuse.out, 0.09, 6.0, COLOR.red)
heater.motor.addConnectionTo(heater.plus, 0, 0, COLOR.Black)
m.ground.addConnectionTo(heater.minus, 0.5, 2.5, COLOR.black)
heater.minus.addConnectionTo(heater.motor, 0, 0, COLOR.Black)
heater_resistor.out.addConnectionTo(heater_resistor.in, 0, 0, COLOR.Black)
heater.plus.addConnectionTo(heater_resistor.out, 0.1, 0.5, COLOR.red)
interior_fan.motor.addConnectionTo(interior_fan.plus, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(interior_fan.minus, 0.5, 0.5, COLOR.black)
interior_fan.minus.addConnectionTo(interior_fan.motor, 0, 0, COLOR.Black)
wipers._2.addConnectionTo(wipers._1, 0, 0, COLOR.Black)
wipers_relay._15.addConnectionTo(wipers._2, 2.5, 4.0, COLOR.blue)
m.ground.addConnectionTo(wipers._3, 0.5, 1.5, COLOR.black)
wipers._3.addConnectionTo(wipers._4, 0, 0, COLOR.Black)
wipers.motor1.addConnectionTo(wipers._5, 0, 0, COLOR.Black)
wipers.motor2.addConnectionTo(wipers._6, 0, 0, COLOR.Black)
wipers._3.addConnectionTo(wipers.motor1, 0, 0, COLOR.Black)
wipers._3.addConnectionTo(wipers.motor2, 0, 0, COLOR.Black)
windshield_washer.motor.addConnectionTo(windshield_washer.plus, 0, 0, COLOR.Black)
m.ground.addConnectionTo(windshield_washer.minus, 0.5, 0.5, COLOR.black)
windshield_washer.minus.addConnectionTo(windshield_washer.motor, 0, 0, COLOR.Black)
brake_pressure_sensor.out.addConnectionTo(brake_pressure_sensor.in, 0, 0, COLOR.Black)
stop_signal_splitter.pin.addConnectionTo(brake_pressure_sensor.out, 2.5, 4.0, COLOR.black)
reverse_lamp_sensor.out.addConnectionTo(reverse_lamp_sensor.in, 0, 0, COLOR.Black)
reverse_lamp.plus.addConnectionTo(reverse_lamp_sensor.out, 3.5, 1.5, COLOR.red)
low_brake_fluid_sensor.out.addConnectionTo(low_brake_fluid_sensor.in, 0, 0, COLOR.Black)
m.ground.addConnectionTo(low_brake_fluid_sensor.out, 0, 0, COLOR.Black)
fuel_level_sensor.out.addConnectionTo(fuel_level_sensor.in, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(fuel_level_sensor.out, 0.5, 0.5, COLOR.black)
m.ground.addConnectionTo(lower_ground_splitter.pin, 0.1, 6.0, COLOR.black)
direct_consumer_fuse_splitter.pin.addConnectionTo(power_splitter.pin, 0.1, 6.0, COLOR.red)
extra_stuff_fuse_splitter.pin.addConnectionTo(power_splitter.pin, 0.2, 16.0, COLOR.red)
ignition_relay._30.addConnectionTo(power_splitter.pin, 0.3, 2.5, COLOR.red)
ignition_switch.in.addConnectionTo(power_splitter.pin, 2.6, 0.5, COLOR.yellow)
light_switch._30.addConnectionTo(power_splitter.pin, 2.0, 0.5, COLOR.white)
brake_pressure_sensor.in.addConnectionTo(power_splitter.pin, 3.0, 2.5, COLOR.brown)
reverse_lamp_sensor.in.addConnectionTo(power_splitter.pin, 3.5, 1.5, COLOR.grey)
low_brake_fluid_warning_light.plus.addConnectionTo(power_splitter.pin, 2.0, 1.5, COLOR.red)
m.ground.addConnectionTo(upper_ground_splitter.pin, 0.1, 1.5, COLOR.black)
coolant_fan_1_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
coolant_fan_2_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
low_beam_relay_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
high_beam_relay_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
side_light_relay_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
turn_signal_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
heater_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
interior_fan_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
wipers_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
windshield_washer_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
car_horn_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
electric_pump_fuse.in.addConnectionTo(direct_consumer_fuse_splitter.pin, 0, 0, COLOR.Black)
coolant_fan_1_fuse.out.addConnectionTo(coolant_fan_1_fuse.in, 0, 0, COLOR.Black)
coolant_fan_1_relay._30.addConnectionTo(coolant_fan_1_fuse.out, 0.2, 2.5, COLOR.red)
coolant_fan_2_fuse.out.addConnectionTo(coolant_fan_2_fuse.in, 0, 0, COLOR.Black)
coolant_fan_2_relay._30.addConnectionTo(coolant_fan_2_fuse.out, 0.2, 2.5, COLOR.white)
low_beam_relay_fuse.out.addConnectionTo(low_beam_relay_fuse.in, 0, 0, COLOR.Black)
low_beam_relay._30.addConnectionTo(low_beam_relay_fuse.out, 0.3, 1.5, COLOR.red)
high_beam_relay_fuse.out.addConnectionTo(high_beam_relay_fuse.in, 0, 0, COLOR.Black)
high_beam_relay._30.addConnectionTo(high_beam_relay_fuse.out, 0.3, 2.5, COLOR.green)
side_light_relay_fuse.out.addConnectionTo(side_light_relay_fuse.in, 0, 0, COLOR.Black)
side_light_relay._30.addConnectionTo(side_light_relay_fuse.out, 0.2, 1.0, COLOR.white)
turn_signal_fuse.out.addConnectionTo(turn_signal_fuse.in, 0, 0, COLOR.Black)
emergency_light_button.emer.addConnectionTo(turn_signal_fuse.out, 2.5, 2.5, COLOR.white)
wipers_fuse.out.addConnectionTo(wipers_fuse.in, 0, 0, COLOR.Black)
wipers._1.addConnectionTo(wipers_fuse.out, 2.5, 4.0, COLOR.red)
windshield_washer_fuse.out.addConnectionTo(windshield_washer_fuse.in, 0, 0, COLOR.Black)
windshield_washer_relay._30.addConnectionTo(windshield_washer_fuse.out, 0.3, 0.5, COLOR.red)
heater_fuse.out.addConnectionTo(heater_fuse.in, 0, 0, COLOR.Black)
heater_relay_1._30.addConnectionTo(heater_fuse.out, 0.3, 0.5, COLOR.red)
heater_relay_2._30.addConnectionTo(heater_fuse.out, 0.3, 0.5, COLOR.white)
interior_fan_fuse.out.addConnectionTo(interior_fan_fuse.in, 0, 0, COLOR.Black)
interior_fan_relay._30.addConnectionTo(interior_fan_fuse.out, 0.3, 0.5, COLOR.red)
car_horn_fuse.out.addConnectionTo(car_horn_fuse.in, 0, 0, COLOR.Black)
car_horn_relay._30.addConnectionTo(car_horn_fuse.out, 0.3, 1.5, COLOR.red)
electric_pump_fuse.out.addConnectionTo(electric_pump_fuse.in, 0, 0, COLOR.Black)
electric_pump_relay._30.addConnectionTo(electric_pump_fuse.out, 0.3, 0.5, COLOR.red)
starter_relay._87.addConnectionTo(starter_relay._30, 0, 0, COLOR.Black)
starter_relay._88.addConnectionTo(starter_relay._30, 0, 0, COLOR.Black)
starter.st.addConnectionTo(starter_relay._87, 2.6, 4.0, COLOR.brown)
control_line_from_ignition_fuse.in.addConnectionTo(starter_relay._88, 0.2, 2.5, COLOR.yellow)
upper_ground_splitter.pin.addConnectionTo(starter_relay._86, 0.4, 0.25, COLOR.black)
starter_relay.coil.addConnectionTo(starter_relay._85, 0, 0, COLOR.Black)
starter_relay._86.addConnectionTo(starter_relay.coil, 0, 0, COLOR.Black)
ignition_relay._87.addConnectionTo(ignition_relay._30, 0, 0, COLOR.Black)
starter_relay_fuse.in.addConnectionTo(ignition_relay._87, 0.2, 2.5, COLOR.white)
upper_ground_splitter.pin.addConnectionTo(ignition_relay._86, 0.4, 0.25, COLOR.black)
ignition_relay.coil.addConnectionTo(ignition_relay._85, 0, 0, COLOR.Black)
ignition_relay._86.addConnectionTo(ignition_relay.coil, 0, 0, COLOR.Black)
coolant_fan_1_relay._87.addConnectionTo(coolant_fan_1_relay._30, 0, 0, COLOR.Black)
coolant_fan_1.plus.addConnectionTo(coolant_fan_1_relay._87, 3.0, 4.0, COLOR.blue)
coolant_control_switch.i.addConnectionTo(coolant_fan_1_relay._86, 1.5, 0.5, COLOR.orange)
coolant_fan_1_relay.coil.addConnectionTo(coolant_fan_1_relay._85, 0, 0, COLOR.Black)
coolant_fan_2_relay._85.addConnectionTo(coolant_fan_1_relay._85, 0.1, 0.5, COLOR.brown)
coolant_fan_1_relay._86.addConnectionTo(coolant_fan_1_relay.coil, 0, 0, COLOR.Black)
coolant_fan_2_relay._87.addConnectionTo(coolant_fan_2_relay._30, 0, 0, COLOR.Black)
coolant_fan_2.plus.addConnectionTo(coolant_fan_2_relay._87, 2.0, 4.0, COLOR.red)
coolant_control_switch.i.addConnectionTo(coolant_fan_2_relay._86, 1.5, 0.5, COLOR.yellow)
coolant_fan_2_relay.coil.addConnectionTo(coolant_fan_2_relay._85, 0, 0, COLOR.Black)
coolant_fan_2_relay._86.addConnectionTo(coolant_fan_2_relay.coil, 0, 0, COLOR.Black)
low_beam_relay._87.addConnectionTo(low_beam_relay._30, 0, 0, COLOR.Black)
left_low_beam.plus.addConnectionTo(low_beam_relay._87, 3.5, 4.0, COLOR.blue)
right_low_beam.plus.addConnectionTo(low_beam_relay._87, 3.5, 4.0, COLOR.white)
upper_ground_splitter.pin.addConnectionTo(low_beam_relay._86, 0.4, 0.25, COLOR.black)
low_beam_relay.coil.addConnectionTo(low_beam_relay._85, 0, 0, COLOR.Black)
low_beam_relay._86.addConnectionTo(low_beam_relay.coil, 0, 0, COLOR.Black)
high_beam_relay._87.addConnectionTo(high_beam_relay._30, 0, 0, COLOR.Black)
left_high_beam.plus.addConnectionTo(high_beam_relay._87, 3.5, 2.5, COLOR.blue)
right_high_beam.plus.addConnectionTo(high_beam_relay._87, 3.5, 2.5, COLOR.white)
high_beam_control_light.plus.addConnectionTo(high_beam_relay._87, 0.5, 0.5, COLOR.yellow)
upper_ground_splitter.pin.addConnectionTo(high_beam_relay._86, 0.4, 0.25, COLOR.black)
high_beam_relay.coil.addConnectionTo(high_beam_relay._85, 0, 0, COLOR.Black)
high_beam_relay._86.addConnectionTo(high_beam_relay.coil, 0, 0, COLOR.Black)
side_light_relay._87.addConnectionTo(side_light_relay._30, 0, 0, COLOR.Black)
side_light_splitter.pin.addConnectionTo(side_light_relay._87, 2.5, 1.0, COLOR.blue)
upper_ground_splitter.pin.addConnectionTo(side_light_relay._86, 0.4, 0.25, COLOR.black)
side_light_relay.coil.addConnectionTo(side_light_relay._85, 0, 0, COLOR.Black)
side_light_relay._86.addConnectionTo(side_light_relay.coil, 0, 0, COLOR.Black)
windshield_washer_relay._87.addConnectionTo(windshield_washer_relay._30, 0, 0, COLOR.Black)
windshield_washer.plus.addConnectionTo(windshield_washer_relay._87, 3.5, 0.5, COLOR.blue)
wipers_relay._86.addConnectionTo(windshield_washer_relay._87, 0.3, 0.5, COLOR.yellow)
upper_ground_splitter.pin.addConnectionTo(windshield_washer_relay._86, 0.4, 0.25, COLOR.black)
windshield_washer_relay.coil.addConnectionTo(windshield_washer_relay._85, 0, 0, COLOR.Black)
windshield_washer_relay._86.addConnectionTo(windshield_washer_relay.coil, 0, 0, COLOR.Black)
turn_signal_relay.p.addConnectionTo(turn_signal_relay.plus, 0, 0, COLOR.Black)
turn_signal_relay.left.addConnectionTo(turn_signal_relay.plus, 0, 0, COLOR.Black)
turn_signal_relay.right.addConnectionTo(turn_signal_relay.plus, 0, 0, COLOR.Black)
turn_signal_relay.kt.addConnectionTo(turn_signal_relay.plus, 0, 0, COLOR.Black)
upper_ground_splitter.pin.addConnectionTo(turn_signal_relay.minus, 1.0, 0.5, COLOR.black)
left_steering_column_turn_signal_switch._49a.addConnectionTo(turn_signal_relay.p, 2.5, 0.5, COLOR.blue)
emergency_light_button.p.addConnectionTo(turn_signal_relay.p, 2.5, 0.5, COLOR.red)
turn_signal_relay.coil_r.addConnectionTo(turn_signal_relay.pb, 0, 0, COLOR.Black)
turn_signal_relay.coil_l.addConnectionTo(turn_signal_relay.lb, 0, 0, COLOR.Black)
turn_signal_control_light.plus.addConnectionTo(turn_signal_relay.kt, 3.0, 0.5, COLOR.orange)
left_turn_signal_repeater.plus.addConnectionTo(turn_signal_relay.left, 1.2, 1.5, COLOR.violet)
left_rear_turn_signal.plus.addConnectionTo(turn_signal_relay.left, 3.5, 1.0, COLOR.violet)
right_turn_signal_repeater.plus.addConnectionTo(turn_signal_relay.right, 2.6, 1.5, COLOR.pink)
right_rear_turn_signal.plus.addConnectionTo(turn_signal_relay.right, 5.0, 1.5, COLOR.white)
turn_signal_relay.minus.addConnectionTo(turn_signal_relay.coil_r, 0, 0, COLOR.Black)
turn_signal_relay.minus.addConnectionTo(turn_signal_relay.coil_l, 0, 0, COLOR.Black)
wipers._4.addConnectionTo(wipers_relay._31b, 2.5, 0.5, COLOR.brown)
wipers_relay.s.addConnectionTo(wipers_relay._15, 0, 0, COLOR.Black)
right_steering_column_switch._53a.addConnectionTo(wipers_relay._15, 2.5, 1.5, COLOR.grey)
wipers_relay._31b.addConnectionTo(wipers_relay.s, 0, 0, COLOR.Black)
right_steering_column_switch._53e.addConnectionTo(wipers_relay.s, 2.5, 4.0, COLOR.red)
wipers_relay.coil1.addConnectionTo(wipers_relay._86, 0, 0, COLOR.Black)
wipers_relay.coil2.addConnectionTo(wipers_relay.j, 0, 0, COLOR.Black)
upper_ground_splitter.pin.addConnectionTo(wipers_relay._31, 0.4, 0.25, COLOR.black)
wipers_relay._31.addConnectionTo(wipers_relay.coil1, 0, 0, COLOR.Black)
wipers_relay._31.addConnectionTo(wipers_relay.coil2, 0, 0, COLOR.Black)
front_head_light_relay._87.addConnectionTo(front_head_light_relay._30, 0, 0, COLOR.Black)
front_head_light.plus.addConnectionTo(front_head_light_relay._87, 2.5, 6.0, COLOR.blue)
upper_ground_splitter.pin.addConnectionTo(front_head_light_relay._86, 0.8, 0.25, COLOR.black)
front_head_light_relay.coil.addConnectionTo(front_head_light_relay._85, 0, 0, COLOR.Black)
front_head_light_relay._86.addConnectionTo(front_head_light_relay.coil, 0, 0, COLOR.Black)
rear_head_light_relay._87.addConnectionTo(rear_head_light_relay._30, 0, 0, COLOR.Black)
rear_head_light.plus.addConnectionTo(rear_head_light_relay._87, 2.5, 6.0, COLOR.blue)
upper_ground_splitter.pin.addConnectionTo(rear_head_light_relay._86, 0.8, 0.25, COLOR.black)
rear_head_light_relay.coil.addConnectionTo(rear_head_light_relay._85, 0, 0, COLOR.Black)
rear_head_light_relay._86.addConnectionTo(rear_head_light_relay.coil, 0, 0, COLOR.Black)
left_head_light_relay._87.addConnectionTo(left_head_light_relay._30, 0, 0, COLOR.Black)
left_head_light.plus.addConnectionTo(left_head_light_relay._87, 3.0, 6.0, COLOR.red)
upper_ground_splitter.pin.addConnectionTo(left_head_light_relay._86, 0.8, 0.25, COLOR.black)
left_head_light_relay.coil.addConnectionTo(left_head_light_relay._85, 0, 0, COLOR.Black)
left_head_light_relay._86.addConnectionTo(left_head_light_relay.coil, 0, 0, COLOR.Black)
right_head_light_relay._87.addConnectionTo(right_head_light_relay._30, 0, 0, COLOR.Black)
right_head_light.plus.addConnectionTo(right_head_light_relay._87, 2.0, 6.0, COLOR.blue)
upper_ground_splitter.pin.addConnectionTo(right_head_light_relay._86, 0.8, 0.25, COLOR.black)
right_head_light_relay.coil.addConnectionTo(right_head_light_relay._85, 0, 0, COLOR.Black)
right_head_light_relay._86.addConnectionTo(right_head_light_relay.coil, 0, 0, COLOR.Black)
heater_relay_1._87.addConnectionTo(heater_relay_1._30, 0, 0, COLOR.Black)
heater_resistor.in.addConnectionTo(heater_relay_1._87, 3.0, 4.0, COLOR.blue)
upper_ground_splitter.pin.addConnectionTo(heater_relay_1._86, 0.4, 0.25, COLOR.black)
heater_relay_1.coil.addConnectionTo(heater_relay_1._85, 0, 0, COLOR.Black)
heater_relay_1._86.addConnectionTo(heater_relay_1.coil, 0, 0, COLOR.Black)
heater_relay_2._87.addConnectionTo(heater_relay_2._30, 0, 0, COLOR.Black)
heater.plus.addConnectionTo(heater_relay_2._87, 3.0, 6.0, COLOR.blue)
upper_ground_splitter.pin.addConnectionTo(heater_relay_2._86, 0.4, 0.25, COLOR.black)
heater_relay_2.coil.addConnectionTo(heater_relay_2._85, 0, 0, COLOR.Black)
heater_relay_2._86.addConnectionTo(heater_relay_2.coil, 0, 0, COLOR.Black)
interior_fan_relay._87.addConnectionTo(interior_fan_relay._30, 0, 0, COLOR.Black)
interior_fan.plus.addConnectionTo(interior_fan_relay._87, 1.0, 0.5, COLOR.blue)
upper_ground_splitter.pin.addConnectionTo(interior_fan_relay._86, 0.4, 0.25, COLOR.black)
interior_fan_relay.coil.addConnectionTo(interior_fan_relay._85, 0, 0, COLOR.Black)
interior_fan_relay._86.addConnectionTo(interior_fan_relay.coil, 0, 0, COLOR.Black)
car_horn_relay._87.addConnectionTo(car_horn_relay._30, 0, 0, COLOR.Black)
car_horn.plus.addConnectionTo(car_horn_relay._87, 3.5, 6.0, COLOR.blue)
upper_ground_splitter.pin.addConnectionTo(car_horn_relay._86, 0.4, 0.25, COLOR.black)
car_horn_relay.coil.addConnectionTo(car_horn_relay._85, 0, 0, COLOR.Black)
car_horn_relay._86.addConnectionTo(car_horn_relay.coil, 0, 0, COLOR.Black)
electric_pump_relay._87.addConnectionTo(electric_pump_relay._30, 0, 0, COLOR.Black)
electric_pump.plus.addConnectionTo(electric_pump_relay._87, 2.5, 2.5, COLOR.blue)
upper_ground_splitter.pin.addConnectionTo(electric_pump_relay._86, 0.4, 0.25, COLOR.black)
electric_pump_relay.coil.addConnectionTo(electric_pump_relay._85, 0, 0, COLOR.Black)
electric_pump_relay._86.addConnectionTo(electric_pump_relay.coil, 0, 0, COLOR.Black)
starter_relay_fuse.out.addConnectionTo(starter_relay_fuse.in, 0, 0, COLOR.Black)
generator.v.addConnectionTo(starter_relay_fuse.out, 3.4, 4.0, COLOR.yellow)
starter_relay._30.addConnectionTo(starter_relay_fuse.out, 0.2, 2.5, COLOR.red)
ignition.data.addConnectionTo(starter_relay_fuse.out, 0.5, 2.5, COLOR.orange)
start_button.in.addConnectionTo(starter_relay_fuse.out, 2.2, 0.5, COLOR.blue)
emergency_light_button.pow.addConnectionTo(starter_relay_fuse.out, 2.0, 1.5, COLOR.orange)
front_head_light_fuse.in.addConnectionTo(extra_stuff_fuse_splitter.pin, 0, 0, COLOR.Black)
rear_head_light_fuse.in.addConnectionTo(extra_stuff_fuse_splitter.pin, 0, 0, COLOR.Black)
left_head_light_fuse.in.addConnectionTo(extra_stuff_fuse_splitter.pin, 0, 0, COLOR.Black)
right_head_light_fuse.in.addConnectionTo(extra_stuff_fuse_splitter.pin, 0, 0, COLOR.Black)
front_head_light_fuse.out.addConnectionTo(front_head_light_fuse.in, 0, 0, COLOR.Black)
front_head_light_relay._30.addConnectionTo(front_head_light_fuse.out, 0.3, 1.5, COLOR.red)
rear_head_light_fuse.out.addConnectionTo(rear_head_light_fuse.in, 0, 0, COLOR.Black)
rear_head_light_relay._30.addConnectionTo(rear_head_light_fuse.out, 0.3, 1.5, COLOR.white)
left_head_light_fuse.out.addConnectionTo(left_head_light_fuse.in, 0, 0, COLOR.Black)
left_head_light_relay._30.addConnectionTo(left_head_light_fuse.out, 0.3, 1.5, COLOR.white)
right_head_light_fuse.out.addConnectionTo(right_head_light_fuse.in, 0, 0, COLOR.Black)
right_head_light_relay._30.addConnectionTo(right_head_light_fuse.out, 0.3, 1.5, COLOR.red)
left_steering_column_light_switch._30.addConnectionTo(control_line_from_ignition_1.pin, 2.5, 0.5, COLOR.violet)
light_switch.x.addConnectionTo(control_line_from_ignition_1.pin, 2.5, 0.5, COLOR.black)
front_head_light_switch.in.addConnectionTo(control_line_from_ignition_1.pin, 2.5, 0.5, COLOR.yellow)
coolant_fan_1_relay._85.addConnectionTo(control_line_from_ignition_2.pin, 0.3, 0.5, COLOR.white)
heater_switch.i.addConnectionTo(control_line_from_ignition_2.pin, 2.5, 0.5, COLOR.red)
interior_fan_switch.in.addConnectionTo(control_line_from_ignition_2.pin, 2.5, 0.5, COLOR.orange)
right_steering_column_switch._53ah.addConnectionTo(control_line_from_ignition_2.pin, 2.5, 0.5, COLOR.pink)
car_horn_switch.in.addConnectionTo(control_line_from_ignition_2.pin, 2.5, 0.5, COLOR.green)
electric_pump_switch.in.addConnectionTo(control_line_from_ignition_2.pin, 2.5, 0.5, COLOR.yellow)
control_line_from_ignition_fuse.out.addConnectionTo(control_line_from_ignition_fuse.in, 0, 0, COLOR.Black)
control_line_from_ignition_1.pin.addConnectionTo(control_line_from_ignition_fuse.out, 0.3, 2.5, COLOR.red)
control_line_from_ignition_2.pin.addConnectionTo(control_line_from_ignition_fuse.out, 0.3, 2.5, COLOR.blue)
front_left_side_light.plus.addConnectionTo(side_light_splitter.pin, 3.5, 1.0, COLOR.red)
front_right_side_light.plus.addConnectionTo(side_light_splitter.pin, 3.5, 1.0, COLOR.white)
rear_left_side_light.plus.addConnectionTo(side_light_splitter.pin, 3.5, 1.0, COLOR.green)
rear_right_side_light.plus.addConnectionTo(side_light_splitter.pin, 3.5, 1.0, COLOR.yellow)
number_plate_light.plus.addConnectionTo(side_light_splitter.pin, 3.5, 1.0, COLOR.brown)
turn_signal_control_light.lamp.addConnectionTo(turn_signal_control_light.plus, 0, 0, COLOR.Black)
turn_signal_control_light.minus.addConnectionTo(turn_signal_control_light.lamp, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(turn_signal_control_light.minus, 0.5, 0.5, COLOR.black)
low_brake_fluid_warning_light.lamp.addConnectionTo(low_brake_fluid_warning_light.plus, 0, 0, COLOR.Black)
engine_overheat_control_light.plus.addConnectionTo(low_brake_fluid_warning_light.plus, 0.2, 0.5, COLOR.green)
low_brake_fluid_warning_light.minus.addConnectionTo(low_brake_fluid_warning_light.lamp, 0, 0, COLOR.Black)
low_brake_fluid_sensor.in.addConnectionTo(low_brake_fluid_warning_light.minus, 2.5, 0.5, COLOR.blue)
high_beam_control_light.lamp.addConnectionTo(high_beam_control_light.plus, 0, 0, COLOR.Black)
high_beam_control_light.minus.addConnectionTo(high_beam_control_light.lamp, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(high_beam_control_light.minus, 0.5, 0.5, COLOR.black)
speedometer_backlight.lamp.addConnectionTo(speedometer_backlight.plus, 0, 0, COLOR.Black)
fuel_level_backlight.plus.addConnectionTo(speedometer_backlight.plus, 0.2, 0.5, COLOR.white)
speedometer_backlight.minus.addConnectionTo(speedometer_backlight.lamp, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(speedometer_backlight.minus, 0.3, 0.5, COLOR.black)
fuel_level_backlight.lamp.addConnectionTo(fuel_level_backlight.plus, 0, 0, COLOR.Black)
engine_temp_backlight.plus.addConnectionTo(fuel_level_backlight.plus, 0.2, 0.5, COLOR.green)
fuel_level_backlight.minus.addConnectionTo(fuel_level_backlight.lamp, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(fuel_level_backlight.minus, 0.3, 0.5, COLOR.black)
fuel_level_gauge.gauge.addConnectionTo(fuel_level_gauge.plus, 0, 0, COLOR.Black)
engine_temp_gauge.plus.addConnectionTo(fuel_level_gauge.plus, 0.3, 0.5, COLOR.yellow)
fuel_level_sensor.in.addConnectionTo(fuel_level_gauge.minus, 2.5, 0.5, COLOR.red)
fuel_level_gauge.minus.addConnectionTo(fuel_level_gauge.gauge, 0, 0, COLOR.Black)
engine_temp_backlight.lamp.addConnectionTo(engine_temp_backlight.plus, 0, 0, COLOR.Black)
oil_pressure_backlight.plus.addConnectionTo(engine_temp_backlight.plus, 0.2, 0.5, COLOR.yellow)
engine_temp_backlight.minus.addConnectionTo(engine_temp_backlight.lamp, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(engine_temp_backlight.minus, 0.3, 0.5, COLOR.black)
engine_temp_gauge.gauge.addConnectionTo(engine_temp_gauge.plus, 0, 0, COLOR.Black)
oil_pressure_gauge.plus.addConnectionTo(engine_temp_gauge.plus, 0.3, 0.5, COLOR.orange)
engine_temp_sensor.in.addConnectionTo(engine_temp_gauge.minus, 2.5, 0.5, COLOR.black)
engine_temp_gauge.minus.addConnectionTo(engine_temp_gauge.gauge, 0, 0, COLOR.Black)
engine_overheat_control_light.lamp.addConnectionTo(engine_overheat_control_light.plus, 0, 0, COLOR.Black)
low_oil_pressure_control_light.plus.addConnectionTo(engine_overheat_control_light.plus, 0.3, 0.5, COLOR.brown)
engine_overheat_control_light.minus.addConnectionTo(engine_overheat_control_light.lamp, 0, 0, COLOR.Black)
engine_overheat_sensor.in.addConnectionTo(engine_overheat_control_light.minus, 2.5, 0.5, COLOR.black)
oil_pressure_backlight.lamp.addConnectionTo(oil_pressure_backlight.plus, 0, 0, COLOR.Black)
voltmeter_backlight.plus.addConnectionTo(oil_pressure_backlight.plus, 0.3, 0.5, COLOR.brown)
oil_pressure_backlight.minus.addConnectionTo(oil_pressure_backlight.lamp, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(oil_pressure_backlight.minus, 0.3, 0.5, COLOR.black)
oil_pressure_gauge.gauge.addConnectionTo(oil_pressure_gauge.plus, 0, 0, COLOR.Black)
voltmeter_gauge.plus.addConnectionTo(oil_pressure_gauge.plus, 0.3, 0.5, COLOR.pink)
oil_pressure_sensor.in.addConnectionTo(oil_pressure_gauge.minus, 2.5, 0.5, COLOR.black)
oil_pressure_gauge.minus.addConnectionTo(oil_pressure_gauge.gauge, 0, 0, COLOR.Black)
low_oil_pressure_control_light.lamp.addConnectionTo(low_oil_pressure_control_light.plus, 0, 0, COLOR.Black)
fuel_level_gauge.plus.addConnectionTo(low_oil_pressure_control_light.plus, 0.3, 0.5, COLOR.white)
low_oil_pressure_control_light.minus.addConnectionTo(low_oil_pressure_control_light.lamp, 0, 0, COLOR.Black)
low_oil_pressure_sensor.in.addConnectionTo(low_oil_pressure_control_light.minus, 2.5, 0.5, COLOR.black)
voltmeter_backlight.lamp.addConnectionTo(voltmeter_backlight.plus, 0, 0, COLOR.Black)
voltmeter_backlight.minus.addConnectionTo(voltmeter_backlight.lamp, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(voltmeter_backlight.minus, 0.3, 0.5, COLOR.black)
voltmeter_gauge.gauge.addConnectionTo(voltmeter_gauge.plus, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(voltmeter_gauge.minus, 0.3, 0.5, COLOR.black)
voltmeter_gauge.minus.addConnectionTo(voltmeter_gauge.gauge, 0, 0, COLOR.Black)
ignition_switch.out.addConnectionTo(ignition_switch.in, 0, 0, COLOR.Black)
ignition_relay._85.addConnectionTo(ignition_switch.out, 2.4, 0.5, COLOR.brown)
start_button.out.addConnectionTo(start_button.in, 0, 0, COLOR.Black)
starter_relay._85.addConnectionTo(start_button.out, 2.2, 0.5, COLOR.white)
coolant_sensor.in.addConnectionTo(coolant_control_switch.d, 3.5, 0.5, COLOR.red)
coolant_control_switch.d.addConnectionTo(coolant_control_switch.i, 0, 0, COLOR.Black)
coolant_control_switch.u.addConnectionTo(coolant_control_switch.i, 0, 0, COLOR.Black)
lower_ground_splitter.pin.addConnectionTo(coolant_control_switch.u, 0.5, 0.5, COLOR.black)
light_switch._58.addConnectionTo(light_switch._30, 0, 0, COLOR.Black)
speedometer_backlight.plus.addConnectionTo(light_switch._58, 0.5, 1.0, COLOR.red)
side_light_relay._85.addConnectionTo(light_switch._58, 2.5, 0.5, COLOR.green)
light_switch._56.addConnectionTo(light_switch.x, 0, 0, COLOR.Black)
left_steering_column_light_switch._56.addConnectionTo(light_switch._56, 1.5, 0.5, COLOR.blue)
turn_signal_relay.pb.addConnectionTo(emergency_light_button.pb, 2.5, 0.5, COLOR.green)
emergency_light_button.pb.addConnectionTo(emergency_light_button.p, 0, 0, COLOR.Black)
emergency_light_button.lb.addConnectionTo(emergency_light_button.p, 0, 0, COLOR.Black)
turn_signal_relay.lb.addConnectionTo(emergency_light_button.lb, 1000.0, 1000.0, COLOR.brown)
emergency_light_button.plus.addConnectionTo(emergency_light_button.pow, 0, 0, COLOR.Black)
turn_signal_relay.plus.addConnectionTo(emergency_light_button.plus, 2.0, 2.5, COLOR.grey)
emergency_light_button.plus.addConnectionTo(emergency_light_button.emer, 0, 0, COLOR.Black)
front_head_light_switch.out.addConnectionTo(front_head_light_switch.in, 0, 0, COLOR.Black)
rear_head_light_switch.in.addConnectionTo(front_head_light_switch.in, 0.1, 0.5, COLOR.grey)
front_head_light_relay._85.addConnectionTo(front_head_light_switch.out, 2.5, 0.5, COLOR.white)
rear_head_light_switch.out.addConnectionTo(rear_head_light_switch.in, 0, 0, COLOR.Black)
left_head_light_switch.in.addConnectionTo(rear_head_light_switch.in, 0.1, 0.5, COLOR.blue)
rear_head_light_relay._85.addConnectionTo(rear_head_light_switch.out, 2.5, 0.5, COLOR.red)
left_head_light_switch.out.addConnectionTo(left_head_light_switch.in, 0, 0, COLOR.Black)
right_head_light_switch.in.addConnectionTo(left_head_light_switch.in, 0.1, 0.5, COLOR.red)
left_head_light_relay._85.addConnectionTo(left_head_light_switch.out, 2.5, 0.5, COLOR.green)
right_head_light_switch.out.addConnectionTo(right_head_light_switch.in, 0, 0, COLOR.Black)
right_head_light_relay._85.addConnectionTo(right_head_light_switch.out, 2.5, 0.5, COLOR.white)
car_horn_switch.out.addConnectionTo(car_horn_switch.in, 0, 0, COLOR.Black)
car_horn_relay._85.addConnectionTo(car_horn_switch.out, 2.5, 0.5, COLOR.white)
heater_relay_1._85.addConnectionTo(heater_switch.d, 2.5, 0.5, COLOR.green)
heater_switch.d.addConnectionTo(heater_switch.i, 0, 0, COLOR.Black)
heater_switch.u.addConnectionTo(heater_switch.i, 0, 0, COLOR.Black)
heater_relay_2._85.addConnectionTo(heater_switch.u, 2.5, 0.5, COLOR.yellow)
interior_fan_switch.out.addConnectionTo(interior_fan_switch.in, 0, 0, COLOR.Black)
interior_fan_relay._85.addConnectionTo(interior_fan_switch.out, 2.5, 0.5, COLOR.white)
electric_pump_switch.out.addConnectionTo(electric_pump_switch.in, 0, 0, COLOR.Black)
electric_pump_relay._85.addConnectionTo(electric_pump_switch.out, 2.5, 0.5, COLOR.white)
left_steering_column_light_switch._56b.addConnectionTo(left_steering_column_light_switch._56, 0, 0, COLOR.Black)
left_steering_column_light_switch._56a.addConnectionTo(left_steering_column_light_switch._56, 0, 0, COLOR.Black)
low_beam_relay._85.addConnectionTo(left_steering_column_light_switch._56b, 3.5, 0.5, COLOR.green)
high_beam_relay._85.addConnectionTo(left_steering_column_light_switch._56a, 2.5, 0.5, COLOR.red)
left_steering_column_light_switch._56a.addConnectionTo(left_steering_column_light_switch._30, 0, 0, COLOR.Black)
turn_signal_relay.pb.addConnectionTo(left_steering_column_turn_signal_switch._49ar, 2.5, 0.5, COLOR.white)
left_steering_column_turn_signal_switch._49ar.addConnectionTo(left_steering_column_turn_signal_switch._49a, 0, 0, COLOR.Black)
left_steering_column_turn_signal_switch._49al.addConnectionTo(left_steering_column_turn_signal_switch._49a, 0, 0, COLOR.Black)
turn_signal_relay.lb.addConnectionTo(left_steering_column_turn_signal_switch._49al, 2.5, 0.5, COLOR.yellow)
right_steering_column_switch._53.addConnectionTo(right_steering_column_switch._53e, 0, 0, COLOR.Black)
wipers._5.addConnectionTo(right_steering_column_switch._53, 1.5, 2.5, COLOR.white)
right_steering_column_switch.j.addConnectionTo(right_steering_column_switch._53a, 0, 0, COLOR.Black)
right_steering_column_switch._53.addConnectionTo(right_steering_column_switch._53a, 0, 0, COLOR.Black)
right_steering_column_switch._53b.addConnectionTo(right_steering_column_switch._53a, 0, 0, COLOR.Black)
wipers_relay.j.addConnectionTo(right_steering_column_switch.j, 2.5, 0.5, COLOR.orange)
wipers._6.addConnectionTo(right_steering_column_switch._53b, 1.5, 2.5, COLOR.green)
right_steering_column_switch.w.addConnectionTo(right_steering_column_switch._53ah, 0, 0, COLOR.Black)
windshield_washer_relay._85.addConnectionTo(right_steering_column_switch.w, 2.5, 0.5, COLOR.brown)
rear_left_side_light.lamp.addConnectionTo(rear_left_side_light.plus, 0, 0, COLOR.Black)
rear_left_side_light.minus.addConnectionTo(rear_left_side_light.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(rear_left_side_light.minus, 1.0, 0.5, COLOR.black)
left_rear_turn_signal.lamp.addConnectionTo(left_rear_turn_signal.plus, 0, 0, COLOR.Black)
left_rear_turn_signal.minus.addConnectionTo(left_rear_turn_signal.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(left_rear_turn_signal.minus, 0.5, 1.0, COLOR.black)
left_stop_signal.lamp.addConnectionTo(left_stop_signal.plus, 0, 0, COLOR.Black)
left_stop_signal.minus.addConnectionTo(left_stop_signal.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(left_stop_signal.minus, 0.5, 0.5, COLOR.black)
rear_right_side_light.lamp.addConnectionTo(rear_right_side_light.plus, 0, 0, COLOR.Black)
rear_right_side_light.minus.addConnectionTo(rear_right_side_light.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(rear_right_side_light.minus, 1.0, 0.5, COLOR.black)
right_rear_turn_signal.lamp.addConnectionTo(right_rear_turn_signal.plus, 0, 0, COLOR.Black)
right_rear_turn_signal.minus.addConnectionTo(right_rear_turn_signal.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(right_rear_turn_signal.minus, 0.5, 0.5, COLOR.black)
right_stop_signal.lamp.addConnectionTo(right_stop_signal.plus, 0, 0, COLOR.Black)
right_stop_signal.minus.addConnectionTo(right_stop_signal.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(right_stop_signal.minus, 0.5, 0.5, COLOR.black)
number_plate_light.lamp.addConnectionTo(number_plate_light.plus, 0, 0, COLOR.Black)
number_plate_light.minus.addConnectionTo(number_plate_light.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(number_plate_light.minus, 0.5, 1.0, COLOR.black)
reverse_lamp.lamp.addConnectionTo(reverse_lamp.plus, 0, 0, COLOR.Black)
reverse_lamp.minus.addConnectionTo(reverse_lamp.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(reverse_lamp.minus, 0.5, 1.5, COLOR.black)
extra_stop_signal.lamp.addConnectionTo(extra_stop_signal.plus, 0, 0, COLOR.Black)
extra_stop_signal.minus.addConnectionTo(extra_stop_signal.lamp, 0, 0, COLOR.Black)
m.ground.addConnectionTo(extra_stop_signal.minus, 0.5, 0.5, COLOR.black)
left_stop_signal.plus.addConnectionTo(stop_signal_splitter.pin, 1.0, 0.75, COLOR.red)
right_stop_signal.plus.addConnectionTo(stop_signal_splitter.pin, 1.0, 0.75, COLOR.blue)
extra_stop_signal.plus.addConnectionTo(stop_signal_splitter.pin, 1.0, 0.75, COLOR.white)
