from networkx import Graph
from engine import Scheme, Pin, COLOR

from elements.generic_car_elements import *
import elements.uaz3151 as uaz3151

graph = Graph()
uaz = Scheme(graph)

m = Pin(uaz, "Кузов")
ground_switch = SimpleSwitch(uaz, "Размыкатель массы")
akb = Akb(uaz, "Аккумулятор", 12.0)
starter = Starter(uaz, "Стартер", 300, 20)
generator = Generator(uaz, "Генератор", 14.0, 5)
ignition = Pin(uaz, "Система зажигания")
winch = Winch(uaz, "Лебедка", 300)
winch_relay = Relay(uaz, "Реле лебедки")
winch_fuse = Fuse(uaz, "Предохранитель лебедки", 5)
winch_switch = SimpleSwitch(uaz, "Управление лебедкой")
coolant_fan_1 = Fan(uaz, "Э-вент охл ДВС 1", 8)
coolant_fan_2 = Fan(uaz, "Э-вент охл ДВС 2", 8)
coolant_sensor = Sensor(uaz, "Датчик вкл э-вент охл ДВС")
engine_overheat_sensor = Sensor(uaz, "Датчик перегрева охлаждающей жидкости")
engine_temp_sensor = Sensor(uaz, "Датчик температуры охлаждающей жидкости")
low_oil_pressure_sensor = Sensor(uaz, "Датчик низкого давления масла")
oil_pressure_sensor = Sensor(uaz, "Датчик давления масла")
car_horn = CarHorn(uaz, "Гудок", 15)
left_low_beam = Light(uaz, "Левый ближний свет", 5)
left_high_beam = Light(uaz, "Левый дальний свет", 5)
front_left_side_light = Light(uaz, "Передний левый габарит", 0.5)
left_front_turn_signal = Light(uaz, "Левый передний поворотник", 0.5)
left_turn_signal_repeater = Light(uaz, "Левый повторитель поворотника", 0.5)
right_low_beam = Light(uaz, "Правый ближний свет", 5)
right_high_beam = Light(uaz, "Правый дальний свет", 5)
front_right_side_light = Light(uaz, "Передний правый габарит", 0.5)
right_front_turn_signal = Light(uaz, "Правый передний поворотник", 0.5)
right_turn_signal_repeater = Light(uaz, "Правый повторитель поворотника", 0.5)
electric_pump = ElectricPump(uaz, "Электрическая помпа", 6)
front_head_light = Light(uaz, "Передняя люстра", 10)
rear_head_light = Light(uaz, "Задняя люстра", 10)
left_head_light = Light(uaz, "Левая боковая люстра", 10)
right_head_light = Light(uaz, "Правая боковая люстра", 10)
power_fuse = Fuse(uaz, "Силовой предохранитель", 5)
heater = Heater(uaz, "Отопитель салона", 8)
heater_resistor = Resistor(uaz, "Резистор печки салона", 15)
interior_fan = Fan(uaz, "Вентилятор салона", 2)
wipers = Wipers(uaz, "Дворники", 5)
windshield_washer = WindshieldWasher(uaz, "Омыватель лобового стекла", 1)
brake_pressure_sensor = Sensor(uaz, "Датчик нажатия педали тормоза")
reverse_lamp_sensor = Sensor(uaz, "Датчик движения заднего хода")
low_brake_fluid_sensor = Sensor(uaz, "Датчик недостаточного уровня тормозной жидкости")
fuel_level_sensor = Sensor(uaz, "Датчик уровня топлива")
lower_ground_splitter = Pin(uaz, "Нижний разветвитель массы")
power_splitter = Pin(uaz, "Силовой разветвитель")
upper_ground_splitter = Pin(uaz, "Верхний разветвитель массы")
direct_consumer_fuse_splitter = Pin(uaz, "Разветвитель для предохранителей прямых потребителей")
coolant_fan_1_fuse = Fuse(uaz, "Прд э-вент охл ДВС 1", 5)
coolant_fan_2_fuse = Fuse(uaz, "Прд э-вент охл ДВС 2", 5)
low_beam_relay_fuse = Fuse(uaz, "Прд реле ближн света", 5)
high_beam_relay_fuse = Fuse(uaz, "Прд реле дальн света", 5)
side_light_relay_fuse = Fuse(uaz, "Прд реле габаритов", 5)
turn_signal_fuse = Fuse(uaz, "Прд поворотников", 5)
wipers_fuse = Fuse(uaz, "Прд дворников", 5)
windshield_washer_fuse = Fuse(uaz, "Прд моторчика омывайки", 5)
heater_fuse = Fuse(uaz, "Прд отопителя", 5)
interior_fan_fuse = Fuse(uaz, "Прд вентилятора салона", 5)
car_horn_fuse = Fuse(uaz, "Прд гудка", 5)
electric_pump_fuse = Fuse(uaz, "Прд электрической помпы", 5)
starter_relay = Relay5(uaz, "Реле стартера")
ignition_relay = Relay(uaz, "Реле зажигания")
coolant_fan_1_relay = Relay(uaz, "Реле э-вент охл ДВС 1")
coolant_fan_2_relay = Relay(uaz, "Реле э-вент охл ДВС 2")
low_beam_relay = Relay(uaz, "Реле ближнего света")
high_beam_relay = Relay(uaz, "Реле дальнего света")
side_light_relay = Relay(uaz, "Реле габаритов")
windshield_washer_relay = Relay(uaz, "Реле моторчика омывайки")
turn_signal_relay = uaz3151.TurnSignalRelay950(uaz, "Реле поворотников")
wipers_relay = uaz3151.WipersRelay(uaz, "Реле дворников")
front_head_light_relay = Relay(uaz, "Реле передней люстры")
rear_head_light_relay = Relay(uaz, "Реле задней люстры")
left_head_light_relay = Relay(uaz, "Реле левой боковой люстры")
right_head_light_relay = Relay(uaz, "Реле правой боковой люстры")
heater_relay_1 = Relay(uaz, "Реле отопителя (1-я скорость)")
heater_relay_2 = Relay(uaz, "Реле отопителя (2-я скорость)")
interior_fan_relay = Relay(uaz, "Реле вентилятора салона")
car_horn_relay = Relay(uaz, "Реле гудка")
electric_pump_relay = Relay(uaz, "Реле электрической помпы")
starter_relay_fuse = Fuse(uaz, "Прд реле стартера", 5)
extra_stuff_fuse_splitter = Pin(uaz, "Разветвитель для предохранителей доп оборудования")
front_head_light_fuse = Fuse(uaz, "Прд передней люстры", 5)
rear_head_light_fuse = Fuse(uaz, "Прд задней люстры", 5)
left_head_light_fuse = Fuse(uaz, "Прд левой боковой люстры", 5)
right_head_light_fuse = Fuse(uaz, "Прд правой боковой люстры", 5)
control_line_from_ignition_1 = Pin(uaz, "Потребители управляющей линии от зажигания (свет)")
control_line_from_ignition_2 = Pin(uaz, "Потребители управляющей линии от зажигания (прочее)")
control_line_from_ignition_fuse = Fuse(uaz, "Предохранитель потребителей управляющей линии от зажигания", 5)
side_light_splitter = Pin(uaz, "разветвитель габаритов")
turn_signal_control_light = Light(uaz, "Контрольная лампа поворотников", 0.5)
low_brake_fluid_warning_light = Light(uaz, "Контрольная лампа недостаточного уровня тормозной жидкости", 0.5)
high_beam_control_light = Light(uaz, "Контрольная лампа дальнего света", 0.5)
speedometer_backlight = Light(uaz, "Подсветка спидометра", 0.5)
fuel_level_backlight = Light(uaz, "Подсветка датчика уровня топлива", 0.5)
fuel_level_gauge = Gauge(uaz, "Указатель уровня топлива", 0.1)
engine_temp_backlight = Light(uaz, "Подсветка датчика температуры двигателя", 0.5)
engine_temp_gauge = Gauge(uaz, "Указатель температуры двигателя", 0.1)
engine_overheat_control_light = Light(uaz, "Лампа перегрева двигателя", 0.5)
oil_pressure_backlight = Light(uaz, "Подсветка датчика давления масла в двигателе", 0.5)
oil_pressure_gauge = Gauge(uaz, "Указатель давления масла в двигателе", 0.1)
low_oil_pressure_control_light = Light(uaz, "Лампа низкого давления масла в двигателе", 0.5)
voltmeter_backlight = Light(uaz, "Подсветка вольтметра", 0.5)
voltmeter_gauge = Gauge(uaz, "Указатель вольтметра", 0.1)
ignition_switch = SimpleSwitch(uaz, "Выключатель зажигания")
start_button = SimpleSwitch(uaz, "Кнопка Старт")
coolant_control_switch = Switch3States6Pins(uaz, "Переключатель упр э-вент охл ДВС")
light_switch = uaz3151.LightSwitch(uaz, "Выключатель габаритов и ближнего света")
emergency_light_button = uaz3151.EmergencyLightSwitch(uaz, "Кнопка аварийной сигнализации")
front_head_light_switch = SimpleSwitch(uaz, "Выключатель передней люстры")
rear_head_light_switch = SimpleSwitch(uaz, "Выключатель задней люстры")
left_head_light_switch = SimpleSwitch(uaz, "Выключатель левой боковой люстры")
right_head_light_switch = SimpleSwitch(uaz, "Выключатель правой боковой люстры")
car_horn_switch = SimpleSwitch(uaz, "Кнопка гудка")
heater_switch = Switch3States6Pins(uaz, "Переключатель печки")
interior_fan_switch = SimpleSwitch(uaz, "Выключатель салонного вентилятора")
electric_pump_switch = SimpleSwitch(uaz, "Выключатель электрической помпы")
left_steering_column_light_switch = uaz3151.LeftSteeringColumnLightSwitch(uaz, "Левый подрулевой переключатель освещения")
left_steering_column_turn_signal_switch = uaz3151.LeftSteeringColumnTurnSignalSwitch(uaz, "левый подрулевой переключатель поворотников")
right_steering_column_switch = uaz3151.RightSteeringColumnSwitch(uaz, "правый подрулевой переключатель")
rear_left_side_light = Light(uaz, "Задний левый габарит", 0.5)
left_rear_turn_signal = Light(uaz, "Левый задний поворотник", 0.5)
left_stop_signal = Light(uaz, "Левый стоп-сигнал", 2)
rear_right_side_light = Light(uaz, "Задний правый габарит", 0.5)
right_rear_turn_signal = Light(uaz, "Правый задний поворотник", 0.5)
right_stop_signal = Light(uaz, "Правый стоп-сигнал", 2)
number_plate_light = Light(uaz, "Подсветка номера", 0.5)
reverse_lamp = Light(uaz, "Лампа заднего хода", 2)
extra_stop_signal = Light(uaz, "Доп стоп-сигнал", 2)
stop_signal_splitter = Pin(uaz, "разветвитель стоп сигналов")

m.addWireConnectionTo(generator.minus, 0.1, 25.0, COLOR.Black)
ground_switch.pin2.addWireConnectionTo(akb.minus, 0.3, 50.0, COLOR.Black)
akb.plus.addWireConnectionTo(starter.plus, 1.5, 50.0, COLOR.Red)
akb.plus.addWireConnectionTo(winch.plus, 1.5, 50.0, COLOR.Red)
akb.plus.addWireConnectionTo(power_fuse.pin1, 1.35, 25.0, COLOR.Red)
generator.plus.addWireConnectionTo(starter.plus, 1.0, 50.0, COLOR.Red)
#ignition.data.addWireConnectionTo(ignition.ignition_coil_1_pin, 2.5, 2.5, COLOR.Blue)
#ignition.data.addWireConnectionTo(ignition.ignition_coil_2_pin, 2.5, 2.5, COLOR.Blue)
winch.minus.addWireConnectionTo(m, 1.5, 50.0, COLOR.Black)
coolant_fan_1.minus.addWireConnectionTo(m, 0.3, 0.5, COLOR.Black)
coolant_fan_2.minus.addWireConnectionTo(m, 0.3, 0.5, COLOR.Black)
car_horn.minus.addWireConnectionTo(m, 0.5, 2.5, COLOR.Black)
left_low_beam.minus.addWireConnectionTo(m, 1.0, 1.5, COLOR.Black)
left_high_beam.minus.addWireConnectionTo(m, 0.5, 1.0, COLOR.Black)
front_left_side_light.minus.addWireConnectionTo(m, 1.0, 0.5, COLOR.Black)
left_front_turn_signal.minus.addWireConnectionTo(m, 0.5, 1.0, COLOR.Black)
left_turn_signal_repeater.plus.addWireConnectionTo(left_front_turn_signal.plus, 2.0, 0.75, COLOR.Violet)
left_turn_signal_repeater.minus.addWireConnectionTo(m, 0.5, 1.0, COLOR.Black)
right_low_beam.minus.addWireConnectionTo(m, 1.0, 1.5, COLOR.Black)
right_high_beam.minus.addWireConnectionTo(m, 0.5, 1.0, COLOR.Black)
front_right_side_light.minus.addWireConnectionTo(m, 1.0, 0.5, COLOR.Black)
right_front_turn_signal.minus.addWireConnectionTo(m, 0.5, 0.5, COLOR.Black)
right_turn_signal_repeater.plus.addWireConnectionTo(right_front_turn_signal.plus, 3.0, 0.75, COLOR.Red)
right_turn_signal_repeater.minus.addWireConnectionTo(m, 0.5, 0.5, COLOR.Black)
electric_pump.minus.addWireConnectionTo(m, 0.5, 1.5, COLOR.Black)
front_head_light.minus.addWireConnectionTo(m, 2.0, 6.0, COLOR.Black)
rear_head_light.minus.addWireConnectionTo(m, 2.5, 6.0, COLOR.Black)
left_head_light.minus.addWireConnectionTo(m, 3.0, 6.0, COLOR.Black)
right_head_light.minus.addWireConnectionTo(m, 2.0, 6.0, COLOR.Black)
power_fuse.pin2.addWireConnectionTo(power_splitter, 0.09, 6.0, COLOR.Red)
heater.minus.addWireConnectionTo(m, 0.5, 2.5, COLOR.Black)
heater_resistor.pin2.addWireConnectionTo(heater.plus, 0.1, 0.5, COLOR.Red)
interior_fan.minus.addWireConnectionTo(lower_ground_splitter, 0.5, 0.5, COLOR.Black)
wipers._2.addWireConnectionTo(wipers_relay._15, 2.5, 4.0, COLOR.Blue)
wipers._3.addWireConnectionTo(m, 0.5, 1.5, COLOR.Black)
windshield_washer.minus.addWireConnectionTo(m, 0.5, 0.5, COLOR.Black)
brake_pressure_sensor.pin2.addWireConnectionTo(stop_signal_splitter, 2.5, 4.0, COLOR.Black)
reverse_lamp_sensor.pin2.addWireConnectionTo(reverse_lamp.plus, 3.5, 1.5, COLOR.Red)
fuel_level_sensor.pin2.addWireConnectionTo(lower_ground_splitter, 0.5, 0.5, COLOR.Black)
lower_ground_splitter.addWireConnectionTo(m, 0.1, 6.0, COLOR.Black)
power_splitter.addWireConnectionTo(direct_consumer_fuse_splitter, 0.1, 6.0, COLOR.Red)
power_splitter.addWireConnectionTo(extra_stuff_fuse_splitter, 0.2, 16.0, COLOR.Red)
power_splitter.addWireConnectionTo(ignition_relay._30, 0.3, 2.5, COLOR.Red)
power_splitter.addWireConnectionTo(ignition_switch.pin1, 2.6, 0.5, COLOR.Yellow)
power_splitter.addWireConnectionTo(light_switch._30, 2.0, 0.5, COLOR.White)
power_splitter.addWireConnectionTo(brake_pressure_sensor.pin1, 3.0, 2.5, COLOR.Brown)
power_splitter.addWireConnectionTo(reverse_lamp_sensor.pin1, 3.5, 1.5, COLOR.Grey)
power_splitter.addWireConnectionTo(low_brake_fluid_warning_light.plus, 2.0, 1.5, COLOR.Red)
upper_ground_splitter.addWireConnectionTo(m, 0.1, 1.5, COLOR.Black)
coolant_fan_1_fuse.pin2.addWireConnectionTo(coolant_fan_1_relay._30, 0.2, 2.5, COLOR.Red)
coolant_fan_2_fuse.pin2.addWireConnectionTo(coolant_fan_2_relay._30, 0.2, 2.5, COLOR.White)
low_beam_relay_fuse.pin2.addWireConnectionTo(low_beam_relay._30, 0.3, 1.5, COLOR.Red)
high_beam_relay_fuse.pin2.addWireConnectionTo(high_beam_relay._30, 0.3, 2.5, COLOR.Green)
side_light_relay_fuse.pin2.addWireConnectionTo(side_light_relay._30, 0.2, 1.0, COLOR.White)
turn_signal_fuse.pin2.addWireConnectionTo(emergency_light_button.emer, 2.5, 2.5, COLOR.White)
wipers_fuse.pin2.addWireConnectionTo(wipers._1, 2.5, 4.0, COLOR.Red)
windshield_washer_fuse.pin2.addWireConnectionTo(windshield_washer_relay._30, 0.3, 0.5, COLOR.Red)
heater_fuse.pin2.addWireConnectionTo(heater_relay_1._30, 0.3, 0.5, COLOR.Red)
heater_fuse.pin2.addWireConnectionTo(heater_relay_2._30, 0.3, 0.5, COLOR.White)
interior_fan_fuse.pin2.addWireConnectionTo(interior_fan_relay._30, 0.3, 0.5, COLOR.Red)
car_horn_fuse.pin2.addWireConnectionTo(car_horn_relay._30, 0.3, 1.5, COLOR.Red)
electric_pump_fuse.pin2.addWireConnectionTo(electric_pump_relay._30, 0.3, 0.5, COLOR.Red)
starter_relay._87.addWireConnectionTo(starter.st, 2.6, 4.0, COLOR.Brown)
starter_relay._88.addWireConnectionTo(control_line_from_ignition_fuse.pin1, 0.2, 2.5, COLOR.Yellow)
starter_relay._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
ignition_relay._87.addWireConnectionTo(starter_relay_fuse.pin1, 0.2, 2.5, COLOR.White)
ignition_relay._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
coolant_fan_1_relay._87.addWireConnectionTo(coolant_fan_1.plus, 3.0, 4.0, COLOR.Blue)
coolant_fan_1_relay._86.addWireConnectionTo(coolant_control_switch.i, 1.5, 0.5, COLOR.Orange)
coolant_fan_1_relay._85.addWireConnectionTo(coolant_fan_2_relay._85, 0.1, 0.5, COLOR.Brown)
coolant_fan_2_relay._87.addWireConnectionTo(coolant_fan_2.plus, 2.0, 4.0, COLOR.Red)
coolant_fan_2_relay._86.addWireConnectionTo(coolant_control_switch.i, 1.5, 0.5, COLOR.Yellow)
low_beam_relay._87.addWireConnectionTo(left_low_beam.plus, 3.5, 4.0, COLOR.Blue)
low_beam_relay._87.addWireConnectionTo(right_low_beam.plus, 3.5, 4.0, COLOR.White)
low_beam_relay._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
high_beam_relay._87.addWireConnectionTo(left_high_beam.plus, 3.5, 2.5, COLOR.Blue)
high_beam_relay._87.addWireConnectionTo(right_high_beam.plus, 3.5, 2.5, COLOR.White)
high_beam_relay._87.addWireConnectionTo(high_beam_control_light.plus, 0.5, 0.5, COLOR.Yellow)
high_beam_relay._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
side_light_relay._87.addWireConnectionTo(side_light_splitter, 2.5, 1.0, COLOR.Blue)
side_light_relay._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
windshield_washer_relay._87.addWireConnectionTo(windshield_washer.plus, 3.5, 0.5, COLOR.Blue)
windshield_washer_relay._87.addWireConnectionTo(wipers_relay._86, 0.3, 0.5, COLOR.Yellow)
windshield_washer_relay._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
turn_signal_relay.minus.addWireConnectionTo(upper_ground_splitter, 1.0, 0.5, COLOR.Black)
turn_signal_relay.p.addWireConnectionTo(left_steering_column_turn_signal_switch._49a, 2.5, 0.5, COLOR.Blue)
turn_signal_relay.p.addWireConnectionTo(emergency_light_button.p, 2.5, 0.5, COLOR.Red)
turn_signal_relay.kt.addWireConnectionTo(turn_signal_control_light.plus, 3.0, 0.5, COLOR.Orange)
turn_signal_relay.left.addWireConnectionTo(left_turn_signal_repeater.plus, 1.2, 1.5, COLOR.Violet)
turn_signal_relay.left.addWireConnectionTo(left_rear_turn_signal.plus, 3.5, 1.0, COLOR.Violet)
turn_signal_relay.right.addWireConnectionTo(right_turn_signal_repeater.plus, 2.6, 1.5, COLOR.Pink)
turn_signal_relay.right.addWireConnectionTo(right_rear_turn_signal.plus, 5.0, 1.5, COLOR.White)
wipers_relay._31b.addWireConnectionTo(wipers._4, 2.5, 0.5, COLOR.Brown)
wipers_relay._15.addWireConnectionTo(right_steering_column_switch._53a, 2.5, 1.5, COLOR.Grey)
wipers_relay.s.addWireConnectionTo(right_steering_column_switch._53e, 2.5, 4.0, COLOR.Red)
wipers_relay._31.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
front_head_light_relay._87.addWireConnectionTo(front_head_light.plus, 2.5, 6.0, COLOR.Blue)
front_head_light_relay._86.addWireConnectionTo(upper_ground_splitter, 0.8, 0.25, COLOR.Black)
rear_head_light_relay._87.addWireConnectionTo(rear_head_light.plus, 2.5, 6.0, COLOR.Blue)
rear_head_light_relay._86.addWireConnectionTo(upper_ground_splitter, 0.8, 0.25, COLOR.Black)
left_head_light_relay._87.addWireConnectionTo(left_head_light.plus, 3.0, 6.0, COLOR.Red)
left_head_light_relay._86.addWireConnectionTo(upper_ground_splitter, 0.8, 0.25, COLOR.Black)
right_head_light_relay._87.addWireConnectionTo(right_head_light.plus, 2.0, 6.0, COLOR.Blue)
right_head_light_relay._86.addWireConnectionTo(upper_ground_splitter, 0.8, 0.25, COLOR.Black)
heater_relay_1._87.addWireConnectionTo(heater_resistor.pin1, 3.0, 4.0, COLOR.Blue)
heater_relay_1._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
heater_relay_2._87.addWireConnectionTo(heater.plus, 3.0, 6.0, COLOR.Blue)
heater_relay_2._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
interior_fan_relay._87.addWireConnectionTo(interior_fan.plus, 1.0, 0.5, COLOR.Blue)
interior_fan_relay._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
car_horn_relay._87.addWireConnectionTo(car_horn.plus, 3.5, 6.0, COLOR.Blue)
car_horn_relay._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
electric_pump_relay._87.addWireConnectionTo(electric_pump.plus, 2.5, 2.5, COLOR.Blue)
electric_pump_relay._86.addWireConnectionTo(upper_ground_splitter, 0.4, 0.25, COLOR.Black)
starter_relay_fuse.pin2.addWireConnectionTo(generator.v.plus, 3.4, 4.0, COLOR.Yellow)
starter_relay_fuse.pin2.addWireConnectionTo(starter_relay._30, 0.2, 2.5, COLOR.Red)
#starter_relay_fuse.pin2.addWireConnectionTo(ignition.data, 0.5, 2.5, COLOR.Orange)
starter_relay_fuse.pin2.addWireConnectionTo(start_button.pin1, 2.2, 0.5, COLOR.Blue)
starter_relay_fuse.pin2.addWireConnectionTo(emergency_light_button.pow, 2.0, 1.5, COLOR.Orange)
front_head_light_fuse.pin2.addWireConnectionTo(front_head_light_relay._30, 0.3, 1.5, COLOR.Red)
rear_head_light_fuse.pin2.addWireConnectionTo(rear_head_light_relay._30, 0.3, 1.5, COLOR.White)
left_head_light_fuse.pin2.addWireConnectionTo(left_head_light_relay._30, 0.3, 1.5, COLOR.White)
right_head_light_fuse.pin2.addWireConnectionTo(right_head_light_relay._30, 0.3, 1.5, COLOR.Red)
control_line_from_ignition_1.addWireConnectionTo(left_steering_column_light_switch._30, 2.5, 0.5, COLOR.Violet)
control_line_from_ignition_1.addWireConnectionTo(light_switch.x, 2.5, 0.5, COLOR.Black)
control_line_from_ignition_1.addWireConnectionTo(front_head_light_switch.pin1, 2.5, 0.5, COLOR.Yellow)
control_line_from_ignition_2.addWireConnectionTo(coolant_fan_1_relay._85, 0.3, 0.5, COLOR.White)
control_line_from_ignition_2.addWireConnectionTo(heater_switch.i, 2.5, 0.5, COLOR.Red)
control_line_from_ignition_2.addWireConnectionTo(interior_fan_switch.pin1, 2.5, 0.5, COLOR.Orange)
control_line_from_ignition_2.addWireConnectionTo(right_steering_column_switch._53ah, 2.5, 0.5, COLOR.Pink)
control_line_from_ignition_2.addWireConnectionTo(car_horn_switch.pin1, 2.5, 0.5, COLOR.Green)
control_line_from_ignition_2.addWireConnectionTo(electric_pump_switch.pin1, 2.5, 0.5, COLOR.Yellow)
control_line_from_ignition_fuse.pin2.addWireConnectionTo(control_line_from_ignition_1, 0.3, 2.5, COLOR.Red)
control_line_from_ignition_fuse.pin2.addWireConnectionTo(control_line_from_ignition_2, 0.3, 2.5, COLOR.Blue)
side_light_splitter.addWireConnectionTo(front_left_side_light.plus, 3.5, 1.0, COLOR.Red)
side_light_splitter.addWireConnectionTo(front_right_side_light.plus, 3.5, 1.0, COLOR.White)
side_light_splitter.addWireConnectionTo(rear_left_side_light.plus, 3.5, 1.0, COLOR.Green)
side_light_splitter.addWireConnectionTo(rear_right_side_light.plus, 3.5, 1.0, COLOR.Yellow)
side_light_splitter.addWireConnectionTo(number_plate_light.plus, 3.5, 1.0, COLOR.Brown)
turn_signal_control_light.minus.addWireConnectionTo(lower_ground_splitter, 0.5, 0.5, COLOR.Black)
low_brake_fluid_warning_light.plus.addWireConnectionTo(engine_overheat_control_light.plus, 0.2, 0.5, COLOR.Green)
low_brake_fluid_warning_light.minus.addWireConnectionTo(low_brake_fluid_sensor.pin1, 2.5, 0.5, COLOR.Blue)
high_beam_control_light.minus.addWireConnectionTo(lower_ground_splitter, 0.5, 0.5, COLOR.Black)
speedometer_backlight.plus.addWireConnectionTo(fuel_level_backlight.plus, 0.2, 0.5, COLOR.White)
speedometer_backlight.minus.addWireConnectionTo(lower_ground_splitter, 0.3, 0.5, COLOR.Black)
fuel_level_backlight.plus.addWireConnectionTo(engine_temp_backlight.plus, 0.2, 0.5, COLOR.Green)
fuel_level_backlight.minus.addWireConnectionTo(lower_ground_splitter, 0.3, 0.5, COLOR.Black)
fuel_level_gauge.plus.addWireConnectionTo(engine_temp_gauge.plus, 0.3, 0.5, COLOR.Yellow)
fuel_level_gauge.minus.addWireConnectionTo(fuel_level_sensor.pin1, 2.5, 0.5, COLOR.Red)
engine_temp_backlight.plus.addWireConnectionTo(oil_pressure_backlight.plus, 0.2, 0.5, COLOR.Yellow)
engine_temp_backlight.minus.addWireConnectionTo(lower_ground_splitter, 0.3, 0.5, COLOR.Black)
engine_temp_gauge.plus.addWireConnectionTo(oil_pressure_gauge.plus, 0.3, 0.5, COLOR.Orange)
engine_temp_gauge.minus.addWireConnectionTo(engine_temp_sensor.pin1, 2.5, 0.5, COLOR.Black)
engine_overheat_control_light.plus.addWireConnectionTo(low_oil_pressure_control_light.plus, 0.3, 0.5, COLOR.Brown)
engine_overheat_control_light.minus.addWireConnectionTo(engine_overheat_sensor.pin1, 2.5, 0.5, COLOR.Black)
oil_pressure_backlight.plus.addWireConnectionTo(voltmeter_backlight.plus, 0.3, 0.5, COLOR.Brown)
oil_pressure_backlight.minus.addWireConnectionTo(lower_ground_splitter, 0.3, 0.5, COLOR.Black)
oil_pressure_gauge.plus.addWireConnectionTo(voltmeter_gauge.plus, 0.3, 0.5, COLOR.Pink)
oil_pressure_gauge.minus.addWireConnectionTo(oil_pressure_sensor.pin1, 2.5, 0.5, COLOR.Black)
low_oil_pressure_control_light.plus.addWireConnectionTo(fuel_level_gauge.plus, 0.3, 0.5, COLOR.White)
low_oil_pressure_control_light.minus.addWireConnectionTo(low_oil_pressure_sensor.pin1, 2.5, 0.5, COLOR.Black)
voltmeter_backlight.minus.addWireConnectionTo(lower_ground_splitter, 0.3, 0.5, COLOR.Black)
voltmeter_gauge.minus.addWireConnectionTo(lower_ground_splitter, 0.3, 0.5, COLOR.Black)
ignition_switch.pin2.addWireConnectionTo(ignition_relay._85, 2.4, 0.5, COLOR.Brown)
start_button.pin2.addWireConnectionTo(starter_relay._85, 2.2, 0.5, COLOR.White)
coolant_control_switch.d.addWireConnectionTo(coolant_sensor.pin1, 3.5, 0.5, COLOR.Red)
coolant_control_switch.u.addWireConnectionTo(lower_ground_splitter, 0.5, 0.5, COLOR.Black)
light_switch._58.addWireConnectionTo(speedometer_backlight.plus, 0.5, 1.0, COLOR.Red)
light_switch._58.addWireConnectionTo(side_light_relay._85, 2.5, 0.5, COLOR.Green)
light_switch._56.addWireConnectionTo(left_steering_column_light_switch._56, 1.5, 0.5, COLOR.Blue)
emergency_light_button.pb.addWireConnectionTo(turn_signal_relay.pb, 2.5, 0.5, COLOR.Green)
emergency_light_button.lb.addWireConnectionTo(turn_signal_relay.lb, 1000.0, 1000.0, COLOR.Brown)
emergency_light_button.plus.addWireConnectionTo(turn_signal_relay.plus, 2.0, 2.5, COLOR.Grey)
front_head_light_switch.pin1.addWireConnectionTo(rear_head_light_switch.pin1, 0.1, 0.5, COLOR.Grey)
front_head_light_switch.pin2.addWireConnectionTo(front_head_light_relay._85, 2.5, 0.5, COLOR.White)
rear_head_light_switch.pin1.addWireConnectionTo(left_head_light_switch.pin1, 0.1, 0.5, COLOR.Blue)
rear_head_light_switch.pin2.addWireConnectionTo(rear_head_light_relay._85, 2.5, 0.5, COLOR.Red)
left_head_light_switch.pin1.addWireConnectionTo(right_head_light_switch.pin1, 0.1, 0.5, COLOR.Red)
left_head_light_switch.pin2.addWireConnectionTo(left_head_light_relay._85, 2.5, 0.5, COLOR.Green)
right_head_light_switch.pin2.addWireConnectionTo(right_head_light_relay._85, 2.5, 0.5, COLOR.White)
car_horn_switch.pin2.addWireConnectionTo(car_horn_relay._85, 2.5, 0.5, COLOR.White)
heater_switch.d.addWireConnectionTo(heater_relay_1._85, 2.5, 0.5, COLOR.Green)
heater_switch.u.addWireConnectionTo(heater_relay_2._85, 2.5, 0.5, COLOR.Yellow)
interior_fan_switch.pin2.addWireConnectionTo(interior_fan_relay._85, 2.5, 0.5, COLOR.White)
electric_pump_switch.pin2.addWireConnectionTo(electric_pump_relay._85, 2.5, 0.5, COLOR.White)
left_steering_column_light_switch._56b.addWireConnectionTo(low_beam_relay._85, 3.5, 0.5, COLOR.Green)
left_steering_column_light_switch._56a.addWireConnectionTo(high_beam_relay._85, 2.5, 0.5, COLOR.Red)
left_steering_column_turn_signal_switch._49ar.addWireConnectionTo(turn_signal_relay.pb, 2.5, 0.5, COLOR.White)
left_steering_column_turn_signal_switch._49al.addWireConnectionTo(turn_signal_relay.lb, 2.5, 0.5, COLOR.Yellow)
right_steering_column_switch._53.addWireConnectionTo(wipers._5, 1.5, 2.5, COLOR.White)
right_steering_column_switch.j.addWireConnectionTo(wipers_relay.j, 2.5, 0.5, COLOR.Orange)
right_steering_column_switch._53b.addWireConnectionTo(wipers._6, 1.5, 2.5, COLOR.Green)
right_steering_column_switch.w.addWireConnectionTo(windshield_washer_relay._85, 2.5, 0.5, COLOR.Brown)
rear_left_side_light.minus.addWireConnectionTo(m, 1.0, 0.5, COLOR.Black)
left_rear_turn_signal.minus.addWireConnectionTo(m, 0.5, 1.0, COLOR.Black)
left_stop_signal.minus.addWireConnectionTo(m, 0.5, 0.5, COLOR.Black)
rear_right_side_light.minus.addWireConnectionTo(m, 1.0, 0.5, COLOR.Black)
right_rear_turn_signal.minus.addWireConnectionTo(m, 0.5, 0.5, COLOR.Black)
right_stop_signal.minus.addWireConnectionTo(m, 0.5, 0.5, COLOR.Black)
number_plate_light.minus.addWireConnectionTo(m, 0.5, 1.0, COLOR.Black)
reverse_lamp.minus.addWireConnectionTo(m, 0.5, 1.5, COLOR.Black)
extra_stop_signal.minus.addWireConnectionTo(m, 0.5, 0.5, COLOR.Black)
stop_signal_splitter.addWireConnectionTo(left_stop_signal.plus, 1.0, 0.75, COLOR.Red)
stop_signal_splitter.addWireConnectionTo(right_stop_signal.plus, 1.0, 0.75, COLOR.Blue)
stop_signal_splitter.addWireConnectionTo(extra_stop_signal.plus, 1.0, 0.75, COLOR.White)
